### ISSUE TITLE
Error with current Jupyter version

### ISSUE THREAD

**Issue by eulerreich** [tarmstrong/nbdiff#239]
I'm running this on the latest Jupyter version and get the following error

```
/usr/local/lib/python2.7/dist-packages/IPython/nbformat.py:13: ShimWarning: The `IPython.nbformat` package has been deprecated. You should impor
t from nbformat instead.                                                                                                                        
  "You should import from nbformat instead.", ShimWarning)                                                                                      
/usr/local/lib/python2.7/dist-packages/nbformat/current.py:19: UserWarning: nbformat.current is deprecated.                                     

- use nbformat for read/write/validate public API                                                                                               
- use nbformat.vX directly to composing notebooks of a particular version                                                                       

  """)                                                                                                                                          
/usr/local/lib/python2.7/dist-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `
notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.                                                                            
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)                                                                             
Traceback (most recent call last):                                                                                                              
  File "/usr/local/bin/nbdiff", line 9, in <module>                                                                                             
    load_entry_point('nbdiff==1.0.4', 'console_scripts', 'nbdiff')()                                                                            
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point                                                       
    return get_distribution(dist).load_entry_point(group, name)                                                                                 
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point                                                      
    return ep.load()                                                                                                                            
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load                                                                  
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])                                                                     
  File "/home/greg/devwork/nbdiff/nbdiff/commands.py", line 13, in <module>                                                                     
    from .server.local_server import app                                                                                                        
  File "/home/greg/devwork/nbdiff/nbdiff/server/local_server.py", line 8, in <module>                                                           
    class NbFlask(Flask):                                                                                                                       
  File "/home/greg/devwork/nbdiff/nbdiff/server/local_server.py", line 10, in NbFlask                                                           
    IPython.html.__path__[0] + '/templates',                                                                                                    
IndexError: list index out of range
```

**Comment by keflavich** [comment]
I got the same error.  Is this a version mismatch?

EDIT: I have ipython 4.0.0.  Can't tell what version of nbdiff I have because of this crash.

**Comment by joaopcoelho** [comment]
I get the same error as well

Maybe it's a matter of replacing references to the apparently deprecated IPython.nbformat with simply nbformat? 

I'm using python2 and python3 via anaconda, with:
Nbdiff version: 1.0.3 (via pip list)
Jupyter version: 4.0.6

Errors:

/Users/joaopcoelho/anaconda/envs/python2/lib/python2.7/site-packages/IPython/nbformat.py:13: ShimWarning: The `IPython.nbformat` package has been deprecated. You should import from nbformat instead.
  "You should import from nbformat instead.", ShimWarning)

/Users/joaopcoelho/anaconda/envs/python3/lib/python3.5/site-packages/IPython/nbformat.py:13: ShimWarning: The `IPython.nbformat` package has been deprecated. You should import from nbformat instead.
  "You should import from nbformat instead.", ShimWarning)

**Comment by ketch** [comment]
I'm also getting this error.  I was very excited about this tool; is there a fix?  This issue has been open for a year and a half, so I'm wondering if the project is still being maintained?

**Comment by rsperko** [comment]
any information on this error? i have it too

https://xkcd.com/979/
